"""
Module 4: Report Generator
- Compiles all findings into a professional SOC-style report
- Outputs both HTML and TXT formats
"""

import os
from datetime import datetime
from utils.banner import print_success, print_info

# Color mapping for HTML severity levels
SEVERITY_COLOR = {
    "CRITICAL": "#dc2626",
    "HIGH":     "#ea580c",
    "MEDIUM":   "#ca8a04",
    "LOW":      "#16a34a",
    "INFO":     "#2563eb"
}

# Emoji mapping for status icons
STATUS_EMOJI = {
    "PASS": "✅",
    "FAIL": "❌",
    "WARN": "⚠️",
    "INFO": "ℹ️"
}

def _get_risk_level(score):
    """Calculates risk level based on risk score"""
    if score >= 60: return "CRITICAL"
    if score >= 40: return "HIGH"
    if score >= 20: return "MEDIUM"
    if score >= 10: return "LOW"
    return "INFORMATIONAL"

def generate_report(ss7_findings, sms_findings, sim_findings, risk_score, target_url):
    """Main function to generate both reports"""
    os.makedirs("reports", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    txt_path = f"reports/ss7shield_report_{timestamp}.txt"
    html_path = f"reports/ss7shield_report_{timestamp}.html"

    _generate_txt_report(txt_path, ss7_findings, sms_findings,
                         sim_findings, risk_score, target_url, timestamp)
    _generate_html_report(html_path, ss7_findings, sms_findings,
                          sim_findings, risk_score, target_url, timestamp)

    print_success(f"TXT Report  → {txt_path}")
    print_success(f"HTML Report → {html_path}")
    return html_path, txt_path


# ── TXT Report Generation ───────────────────────────────────────────
def _generate_txt_report(path, ss7_findings, sms_findings,
                         sim_findings, risk_score, target_url, ts):
    risk_level = _get_risk_level(risk_score)
    lines = [
        "=" * 70,
        "           SS7SHIELD — SECURITY ASSESSMENT REPORT",
        "=" * 70,
        f"Target      : {target_url}",
        f"Date        : {ts}",
        f"Risk Score  : {risk_score}/100",
        f"Risk Level  : {risk_level}",
        "=" * 70,
        "",
        "[ 1. SS7 VULNERABILITY ASSESSMENT ]",
        "-" * 40,
    ]
    for f in ss7_findings:
        lines.append(f"  [{f['details']['severity']}] {f['details']['name']}")
        lines.append(f"    Impact     : {f['details']['impact']}")
        lines.append(f"    Mitigation : {f['details']['mitigation']}")
        lines.append("")

    lines += ["", "[ 2. SMS 2FA SECURITY CHECKS ]", "-" * 40]
    for f in sms_findings:
        emoji = STATUS_EMOJI.get(f['status'], '•')
        lines.append(f"  {emoji} [{f['severity']}] {f['title']}")
        lines.append(f"      {f['description']}")
        lines.append("")

    lines += ["", "[ 3. SIM SWAP RISK ASSESSMENT ]", "-" * 40]
    for f in sim_findings:
        emoji = STATUS_EMOJI.get(f['status'], '•')
        lines.append(f"  {emoji} [{f['severity']}] {f['title']}")
        lines.append(f"      {f['description']}")
        lines.append("")

    lines += [
        "", "[ 4. RECOMMENDATIONS ]", "-" * 40,
        "  1. Deploy SS7 Firewall — filter ATI, updateLocation from external networks",
        "  2. Implement SMS Home Routing — prevent SMS hijacking",
        "  3. Replace SMS 2FA with TOTP (Google Authenticator) or FIDO2",
        "  4. Add SIM swap detection + notification system",
        "  5. Enforce session invalidation on phone number change",
        "  6. Monitor SS7 traffic for anomalous MAP requests",
        "  7. Integrate carrier-level SIM swap detection API",
        "",
        "[ 5. REFERENCES ]", "-" * 40,
        "  • Tobias Engel — SS7: Locate. Track. Manipulate. (CCC 2014)",
        "  • NIST SP 800-63B — SMS OTP not recommended for authentication",
        "  • 3GPP TS 29.002 — MAP specification",
        "  • GSMA FS.11 — SS7 Interconnect Security Monitoring",
        "",
        "=" * 70,
        "  Generated by SS7Shield — SOC Portfolio Tool",
        "=" * 70,
    ]

    with open(path, 'w') as f:
        f.write('\n'.join(lines))


# ── HTML Report Generation ──────────────────────────────────────────
def _generate_html_report(path, ss7_findings, sms_findings,
                           sim_findings, risk_score, target_url, ts):
    risk_level = _get_risk_level(risk_score)
    risk_color = "#dc2626" if risk_score >= 60 else "#ea580c" if risk_score >= 40 else "#ca8a04"

    # Build sections
    ss7_rows = ""
    for f in ss7_findings:
        color = SEVERITY_COLOR.get(f['details']['severity'], '#6b7280')
        ss7_rows += f"""
        <tr>
          <td><span class="badge" style="background:{color}">{f['details']['severity']}</span></td>
          <td><strong>{f['details']['name']}</strong></td>
          <td>{f['details']['impact']}</td>
          <td>{f['details']['mitigation']}</td>
        </tr>"""

    sms_rows = ""
    for f in sms_findings:
        color = SEVERITY_COLOR.get(f['severity'], '#6b7280')
        emoji = STATUS_EMOJI.get(f['status'], '•')
        sms_rows += f"""
        <tr>
          <td>{emoji}</td>
          <td><span class="badge" style="background:{color}">{f['severity']}</span></td>
          <td><strong>{f['title']}</strong></td>
          <td>{f['description']}</td>
        </tr>"""

    sim_rows = ""
    for f in sim_findings:
        color = SEVERITY_COLOR.get(f['severity'], '#6b7280')
        emoji = STATUS_EMOJI.get(f['status'], '•')
        sim_rows += f"""
        <tr>
          <td>{emoji}</td>
          <td><span class="badge" style="background:{color}">{f['severity']}</span></td>
          <td><strong>{f['title']}</strong></td>
          <td>{f['description']}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SS7Shield Report</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; }}
  .header {{ background: linear-gradient(135deg, #1e293b, #0f172a);
             border-bottom: 2px solid #dc2626; padding: 30px 40px; }}
  .header h1 {{ font-size: 2rem; color: #dc2626; letter-spacing: 2px; }}
  .header p  {{ color: #94a3b8; margin-top: 6px; }}
  .meta {{ display: flex; gap: 30px; margin-top: 20px; flex-wrap: wrap; }}
  .meta-item {{ background: #1e293b; padding: 10px 20px; border-radius: 8px;
                border-left: 3px solid #dc2626; }}
  .meta-item label {{ font-size: 0.75rem; color: #64748b; text-transform: uppercase; }}
  .meta-item span  {{ display: block; font-size: 1.1rem; font-weight: bold;
                      color: {risk_color}; }}
  .container {{ max-width: 1100px; margin: 30px auto; padding: 0 20px; }}
  .section {{ background: #1e293b; border-radius: 12px; margin-bottom: 30px;
              border: 1px solid #334155; overflow: hidden; }}
  .section-header {{ background: #0f172a; padding: 16px 24px;
                     border-bottom: 1px solid #334155; }}
  .section-header h2 {{ color: #38bdf8; font-size: 1.1rem; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ background: #0f172a; padding: 12px 16px; text-align: left;
        font-size: 0.8rem; color: #64748b; text-transform: uppercase;
        letter-spacing: 1px; }}
  td {{ padding: 12px 16px; border-bottom: 1px solid #334155;
        font-size: 0.9rem; vertical-align: top; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover {{ background: #0f172a; }}
  .badge {{ display: inline-block; padding: 3px 10px; border-radius: 20px;
            font-size: 0.75rem; font-weight: bold; color: white; }}
  .footer {{ text-align: center; padding: 20px; color: #475569; font-size: 0.85rem; }}
</style>
</head>
<body>
<div class="header">
  <h1>⚡ SS7SHIELD</h1>
  <p>SS7 Vulnerability Assessment & SMS Security Report</p>
  <div class="meta">
    <div class="meta-item">
      <label>Target</label>
      <span style="color:#e2e8f0">{target_url}</span>
    </div>
    <div class="meta-item">
      <label>Risk Score</label>
      <span>{risk_score}/100</span>
    </div>
    <div class="meta-item">
      <label>Risk Level</label>
      <span>{risk_level}</span>
    </div>
    <div class="meta-item">
      <label>Generated</label>
      <span style="color:#e2e8f0;font-size:0.9rem">{ts}</span>
    </div>
  </div>
</div>
<div class="container">
  <div class="section">
    <div class="section-header"><h2>MODULE 1: SS7 VULNERABILITY ASSESSMENT</h2></div>
    <table>
      <thead><tr><th>Severity</th><th>Vulnerability</th><th>Impact</th><th>Mitigation</th></tr></thead>
      <tbody>{ss7_rows}</tbody>
    </table>
  </div>
  <div class="section">
    <div class="section-header"><h2>MODULE 2: SMS 2FA SECURITY CHECKS</h2></div>
    <table>
      <thead><tr><th></th><th>Severity</th><th>Test</th><th>Description</th></tr></thead>
      <tbody>{sms_rows}</tbody>
    </table>
  </div>
  <div class="section">
    <div class="section-header"><h2>MODULE 3: SIM SWAP RISK ASSESSMENT</h2></div>
    <table>
      <thead><tr><th></th><th>Severity</th><th>Test</th><th>Description</th></tr></thead>
      <tbody>{sim_rows}</tbody>
    </table>
  </div>
</div>
<div class="footer">Generated by SS7Shield — SOC Analyst Portfolio Project</div>
</body>
</html>"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
